# Tarea 2

Alejandra Yamamoto

1) Consideren la función
$$
z_{n+1} = z_n^2 + c, 
$$

con c = -0.123 + 0.745im. Definan una malla de valores iniciales $z_0$ en el intervalo $[-1,1]\times [-1,1]$ (parte real $\times$ parte imaginaria).

- ¿Cuantos valores finitos distintos (en el intervalo $[-1,1]\times [-1,1]$) se pueden obtener después de un gran número de iteraciones?

- Usando un color distinto para cada uno, grafiquen en el plano $\textrm{Re}(z) - \textrm{Im}(z)$ el conjunto obtenido.

In [ ]:
using Plots

In [28]:
c = -0.123 + 0.745im

-0.123 + 0.745im

In [ ]:
z(n) = z^2 + (c = -0.123 + 0.745im)

In [46]:
?zeros

search: zeros spzeros nonzeros count_zeros set_zero_subnormals



```
zeros(type, dims)
```

Create an array of all zeros of specified type. The type defaults to Float64 if not specified.

```
zeros(A)
```

Create an array of all zeros with the same element type and shape as `A`.


In [ ]:
typeof(-0.123 + 0.745im)

In [121]:
function malla(n::Int64) #n es el índice i o j de la malla o matriz
    
A = zeros(Complex128,n,n)
real = collect(linspace(-1,1,n))
imag = collect(linspace(-1,1,n))
    
    for i in 1:n
        for j in 1:n
            A[j,i] = real[i]-imag[j]*im
        end
    
    end
    
return A

end

malla (generic function with 1 method)

In [122]:
A = malla(3)

3x3 Array{Complex{Float64},2}:
 -1.0+1.0im  0.0+1.0im  1.0+1.0im
 -1.0-0.0im  0.0-0.0im  1.0-0.0im
 -1.0-1.0im  0.0-1.0im  1.0-1.0im

In [123]:
A

3x3 Array{Complex{Float64},2}:
 -1.0+1.0im  0.0+1.0im  1.0+1.0im
 -1.0-0.0im  0.0-0.0im  1.0-0.0im
 -1.0-1.0im  0.0-1.0im  1.0-1.0im

LoadError: LoadError: MethodError: `getindex` has no method matching getindex(::Function, ::Int64)
while loading In[136], in expression starting on line 1

In [186]:
A[3,1]

-1.0 - 1.0im

In [187]:
A[9]

1.0 - 1.0im

In [188]:
A[1]

-1.0 + 1.0im

In [189]:
ans

-1.0 + 1.0im

In [190]:
ans^2

0.0 - 2.0im

In [191]:
ans + (-0.123 + 0.745im)

-0.123 - 1.255im

In [192]:
ans^2 + (-0.123 + 0.745im)

-1.6828959999999997 + 1.0537299999999998im

In [193]:
ans^2 + (-0.123 + 0.745im)

1.5987920339159993 - 2.801636004159999im

In [170]:
ans + (-0.123 + 0.745im)

2-element Array{Complex{Float64},1}:
  -0.123+0.745im  
 -1.8059+1.79873im

In [183]:
(-1.0 + 1.0im)^2 + (-0.123 + 0.745im)

-0.123 - 1.255im

In [138]:
A

3x3 Array{Complex{Float64},2}:
 -1.0+1.0im  0.0+1.0im  1.0+1.0im
 -1.0-0.0im  0.0-0.0im  1.0-0.0im
 -1.0-1.0im  0.0-1.0im  1.0-1.0im

In [129]:
zeros(Float64,3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [220]:
function iterar1(m::Int64, n::Int64, i::Int64) #Función  que itera específicamente una sóla entrada de A
    v = zeros(Complex128, n)
    
    z0 = (-1.0 + 1.0im)^2 + (-0.123 + 0.745im)
    
    #for k in 1:n
        for l in 2:m
        z0 = z0^2 + (-0.123 + 0.745im)
        
        end
        #push!(v,z0)
        v[i] = z0 
    #end
    return v
end
    
    

iterar1 (generic function with 3 methods)

In [333]:
#Función prueba que itera m veces todas las entradas de la malla n^2.   

function iterarpr(n::Int64, m::Int64) 
    
    A = zeros(Complex128,n,n) #Matriz A de ceros complejos de nxn
    real = collect(linspace(-1,1,n)) #vector real de n entradas
    imag = collect(linspace(-1,1,n)) #vector imag de n entradas
    
    for i in 1:n 
        for j in 1:n
            A[j,i] = real[i] - imag[j]*im
        end
    
    end
    
#return A

 
    m_iter = zeros(Complex128,n,n) #Arreglo vacío
    contador = 0
    
    for l in 1:n*n 
        z0 = A[l] 
    
        
        for k in 1:m
            #for l in 2:m
                z0 = z0^2 + (-0.123 + 0.745im)
           
        end
        
        m_iter[l] = z0 
        
        !isnan(m_iter[l]) ? (contador = contador + 1) : contador = contador
         
    end
    
    val_finitos = Array(Complex128, contador)
    
    
    
    q = 1 #contador 
    for p in 1:n*n
        
        if !isnan(m_iter[p]) 
            val_finitos[q] = m_iter[p]
            #q = q + 1
            q =+ 1
        end
    end
    
    return A, m_iter, contador, val_finitos
    
end



iterarpr (generic function with 2 methods)

In [341]:
iterarpr(5,100)

(
5x5 Array{Complex{Float64},2}:
 -1.0+1.0im  -0.5+1.0im  0.0+1.0im  0.5+1.0im  1.0+1.0im
 -1.0+0.5im  -0.5+0.5im  0.0+0.5im  0.5+0.5im  1.0+0.5im
 -1.0-0.0im  -0.5-0.0im  0.0-0.0im  0.5-0.0im  1.0-0.0im
 -1.0-0.5im  -0.5-0.5im  0.0-0.5im  0.5-0.5im  1.0-0.5im
 -1.0-1.0im  -0.5-1.0im  0.0-1.0im  0.5-1.0im  1.0-1.0im,

5x5 Array{Complex{Float64},2}:
 NaN+NaN*im          NaN+NaN*im               NaN+NaN*im   …  NaN+NaN*im
 NaN+NaN*im  0.000890582+0.000260601im        NaN+NaN*im      NaN+NaN*im
 NaN+NaN*im          NaN+NaN*im         -0.122999+0.745im     NaN+NaN*im
 NaN+NaN*im          NaN+NaN*im               NaN+NaN*im      NaN+NaN*im
 NaN+NaN*im          NaN+NaN*im               NaN+NaN*im      NaN+NaN*im,

3,Complex{Float64}[0.000890581677636948 + 0.00026060116266768407im,0.0 + 0.0im,2.2150050006e-314 + 2.2150050006e-314im])

In [243]:
#Prueba, de la primer entrada
(-1.0+1.0im)^2 + (-0.123 + 0.745im)

-0.123 - 1.255im

In [276]:
(-0.123 - 1.255im)^2 + (-0.123 + 0.745im)

-1.6828959999999997 + 1.0537299999999998im

In [245]:
#Prueba de la segunda entrada
(-1.0-1.0im)^2 + (-0.123 + 0.745im)

-0.123 + 2.745im

In [246]:
(-0.123 + 2.745im)^2 + (-0.123 + 0.745im)

-7.642896000000001 + 0.06972999999999996im

In [278]:
(-7.642896000000001 + 0.06972999999999996im)^2 + (-0.123 + 0.745im)

58.28599699391602 - 0.32087827615999964im

In [247]:
#Prueba de la tercer entrada
(1.0+1.0im)^2 + (-0.123 + 0.745im)

-0.123 + 2.745im

In [248]:
(-0.123 + 2.745im)^2 + (-0.123 + 0.745im)

-7.642896000000001 + 0.06972999999999996im

In [249]:
#Prueba de la cuarta entrada
(1.0-1.0im)^2 + (-0.123 + 0.745im)

-0.123 - 1.255im

In [250]:
(-0.123 - 1.255im)^2 + (-0.123 + 0.745im)

-1.6828959999999997 + 1.0537299999999998im

In [127]:
for z in A
    ite = zeros(Float64,9)
    z = z^2 + (-0.123 + 0.745im)
end

In [ ]:
A = 

2) Usando la función compute_roots vista en clase, o en alguna variación propuesta por ustedes, definan (en Julia) el mapeo
$$
x_{n+1} = B(x_{n}) = 2x_n \mod 1.
$$
Obtengas los puntos fijos de este mapeo numéricamente. Los puntos fijos del mapeo son aquéllos que se mapean en si mismos, es decir, $x_{n} = B(x_{n})$. Este cálculo se puede hacer a mano, lo que debe usarse para comprobar que la implementación numérica funciona bien.
Pensando en que la estabilidad de un punto fijo es el comportamiento que se observa de los iterados (a priori un número infinito) al considerar pequeñas desviaciones del punto fijo, ¿cuál es la estabilidad de los puntos fijos que se obtiene numéricamente, digamos, después de 100 iteraciones? ¿Pueden encontrar una explicación analítica de la observación numérica?

In [345]:
function compute_roots()
    initial_conditions = -20:0.125:20
    roots = similar(initial_conditions)

    for (j, x_0) in enumerate(initial_conditions)
        x = x_0

        # 100 iterations of Newton's method
        for i in 1:100
            #x = x - f(x) / f´(x)
            x = x -  2x / 2
        end

        roots[j] = x
    end
    
    roots
end

compute_roots (generic function with 1 method)

In [346]:
compute_roots()

321-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [ ]:
lista_aleat = Array(Float64,1)
for i in 